[package]
name = "curve25519_python"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
curve25519-dalek = "4.1.3"

[lib]
name = "curve25519_python"
crate-type = ["cdylib"]